[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' https: data: blob:;"
    X-Frame-Options = "SAMEORIGIN"
    Cache-Control = "no-cache"

# Proxy playlist requests through Netlify to avoid CORS issues
[[redirects]]
  from = "/api/playlist"
  to = "https://script.google.com/macros/s/AKfycbwtvhLHhbR7Q7vvt3ky4Aup0ZOFtJcZNGJLdZUuyiWpbeyzd73S6TjKrm-JbaygSe0R/exec"
  status = 200
  force = true
