[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' https: data: blob:;"
    X-Frame-Options = "SAMEORIGIN"
    Cache-Control = "no-cache"

# Proxy playlist requests through Netlify to avoid CORS issues
[[redirects]]
  from = "/api/playlist"
  to = "https://script.google.com/macros/s/AKfycbwtvhLHhbR7Q7vvt3ky4Aup0ZOFtJcZNGJLdZUuyiWpbeyzd73S6TjKrm-JbaygSe0R/exec"
  status = 200
  force = true

# TV 2 proxy
[[redirects]]
  from = "/api/playlist2"
  to = "https://script.google.com/macros/s/AKfycbxhTGckQC_giAkPc_gm4Z79ckZdCkVfEUt5ekkm9QvdBB0oNzdPeWq8J38j9-fSnBF7Kg/exec"
  status = 200
  force = true

# TV 3 proxy
[[redirects]]
  from = "/api/playlist3"
  to = "https://script.google.com/macros/s/AKfycbyU6BytSKaU_qNXENdDIyuCq46hccQH-d7cGh9dfFn1_k_PI4KRlcVudsG4LbH-OybbzA/exec"
  status = 200
  force = true
